### ISSUE TITLE
[BUG] React dependencies were not found

### ISSUE THREAD

**Issue by magpiedigital** [Typeform/embed#142]
**Describe the bug**
We use the typeform embed on a Vue.js web app. We started getting an error and decided to update from 0.9.0. Now when building our project we get an error saying we're messing react and react-dom dependencies.

**To Reproduce**
Vue.js project.
Install package and build project

- OS: MacOS
- Browser: build stage bug
- Embed SDK Version: 0.31.1
- NodeJS version: 10.22.0
- NPM version: 6.14.6

**Comment by mathio** [comment]
Hello @magpiedigital. Embed lib requires react lib at the moment. Since it is a peer dependency **you need to install it into your project yourself**:
```
yarn add react react-dom
```

This is a benefit for react projects to reuse react from the project and not introduce a new one. I know this is not ideal for non-react projects such as yours because you will need to add react.

I can tell you we are currently working on a new version of the embed lib that will not require react dependency. We will keep you updated.

**Comment by magpiedigital** [comment]
Ok, that's a shame. For now I'll use the cdn version
