### ISSUE TITLE
onQuestionChanged to pass question number as parameter

### ISSUE THREAD

**Issue by jaunt** [Typeform/embed#214]
Feature request:  Considering that the survey progress logic in the footer doesn't work well (on our survey, it gets to 90%, jumps back to 70%, builds to 90%, back to 70% etc),  I would love to simply retrieve the current question number and show progress myself.

For example, if I know my survey has 40 questions, I can simply take the percentage complete.

**Comment by mathio** [comment]
I have added this to the backlog along with #199 as its related.

We display the form progress % based on current list of questions which could change based on logic jumps. The moment the logic jump fires the form length changes and the calculation changes too [See details on Progress widget in help center.](https://help.typeform.com/hc/en-us/articles/360029619371-Progress-widget-Classic-builder-) 

We can send question ID or ref as payload to `onQuestionChanged`. I think we could also send you the number of the question - order in which the question was displayed if that helps. However it will be up to you to determine the % of progress, because the total number of questions can change based on logic jumps in your form.

**Comment by jaunt** [comment]
For us, a pessimistic algorithm would be much better than one that bounces backward several times.  For example, if your progress algorithm calculated and assumed the longest path through the survey, then worst case progress would suddenly jump more than expected.  But that's totally fine.  What's crazy is when you get so close to 90% then it jumps back to 70%, several times! :-)

**Comment by mathio** [comment]
I am sorry I thought this would be more straightforward to implement but it is not.

Would it be sufficient for your use case to receive question ref? See issue #199. 

If not, I will have to defer you to our @Typeform/conversations team.

**Comment by jaunt** [comment]
Thanks for the help.  That probably would be useful, though would take some hacks to get working nicely.
