### ISSUE TITLE
Error when embedding

### ISSUE THREAD

**Issue by victorlaforga** [Typeform/embed#247]
Who could help me out? I am trying to render my form on my site.

<img width="834" alt="Schermafbeelding 2021-05-25 om 18 37 52" src="https://user-images.githubusercontent.com/37700441/119535477-54bff400-bd88-11eb-8fd8-ccb88b64dbf0.png">

**Comment by antoniofull** [comment]
Hi @victorlaforga  could you please create a minimal reproduction of the issue so that we can look at the code?  A jsfiddle would be ok.
Which version of Embed are you using? We have released recently a [new Embed version](https://github.com/Typeform/embed/tree/main/packages/embed) and we have also released a [React Library](https://github.com/Typeform/embed/tree/main/packages/embed-react) 

Looking at the screenshot I see that you are calling makeWidget inside a React component, be careful to call it on `componentDidMount` or if you use hooks on `useEffect` and make sure that the window object is available.

**Comment by prilutskiy** [comment]
Indeed, there's no such function as `makeWidget` in embed `v1.0`, please use `createWidget` instead: https://github.com/Typeform/embed/tree/main/packages/embed

**Comment by victorlaforga** [comment]
Sorry for not reproducing the issue. Here is my code
```
import React, { useRef, useEffect } from 'react';
import { createWidget } from "@typeform/embed";
import "@typeform/embed/build/css/widget.css"; // import necessary CSS

const MyTypeformEmbed = () => {
  const container = useRef(); 

  useEffect(() => {
    createWidget("CWcJdwc7", { container: container.current });
  }, []);

  return <div ref={container}></div>;
};


export default MyTypeformEmbed;
```

**Comment by mathio** [comment]
Hello @victorlaforga , the code you provided works just fine for me. You can check it out in a CodeSandbox here:

https://codesandbox.io/s/determined-haze-n7iuw?file=/src/App.js

**Comment by victorlaforga** [comment]
Yes it works now thanks!
