### ISSUE TITLE
Angular+Typescript embed error

### ISSUE THREAD

**Issue by AdrienVictor** [Typeform/embed#249]
Hello,

I'm having some issue while trying to embed the new version of the @typeform/embed package.
Following the instruction, I got the latest package version and my code is as follow on angular 11:

```
import { Component, OnInit } from '@angular/core';
import { createPopup, createWidget } from '@typeform/embed';
import '@typeform/embed/build/css/widget.css';

@Component({
  selector: 'app-application-view',
  templateUrl: './application-view.component.html',
  styleUrls: ['./application-view.component.scss'],
})
export class ApplicationViewComponent implements OnInit {
  constructor() {}

  ngOnInit(): void {
    createWidget('form-id', { container: document.querySelector('#form') });
  }

  openTypeform() {
    createPopup('form-id', { size: 90 });
  }

}
```

The **createPopup** function doesn't do anything, no errors but nothing happens either.

The **createWidget** function brings the following error while being displayed: 

![image](https://user-images.githubusercontent.com/46904762/119646611-082bf580-be28-11eb-8cd3-3a4788da21b5.png)

Any thoughts and fixes for those two issues? I am particularly looking for the createPopup fix :). 

thanks!

**Comment by mathio** [comment]
Hello @AdrienVictor ,

it is hard to tell about `createPopup`, since you did not provide the code that calls `openTypeform` method. One thing that comes to my mind is that you just created the popup but did not open it - you need to call `open()` or `toggle()` on the popup (see [example](https://github.com/Typeform/embed/blob/main/packages/demo-html/public/popup-js.html)).

As for `createWidget` it is hard to tell as well since we do not see the `#form` element (most likely in `application-view.component.html`?).

The error you posted is related to [Content Security Policy headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP). It looks like you are trying to embed the form in a website that is not served securely via HTTPS. However we define `content-security-policy-report-only` header which [should show error in console, but not affect any functionality](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy-Report-Only).

**Comment by AdrienVictor** [comment]
Hi @mathio !

I'm sorry but I don't get what you mean. I cannot use an HTML script with typeScript. I am calling the function as follow in my HTML:

`      <button nbButton hero status="info" shape="round" (click)="openTypeform()">APPLY test</button>
`

I followed the npm package installation guide and based on what is the readme I don't need to do anything in the HTML and just pass the createPopup function in my ts file:

`import { createWidget } from '@typeform/embed'

import '@typeform/embed/build/css/widget.css'

createWidget('<form-id>', { container: document.querySelector('#form') })
`

I just replaced the createdWidget by createPopup in my openTypeform function and calling it (onCLick) in my angular framework in the HTML.

I'm confused by the documentation you shared to me, it doesn't really resemble my case at all.

Is there an actual support for the embed typeform on angular yet? 

Thanks a lot.

Cheers!

**Comment by mathio** [comment]
It is hard to tell when you do not provide full code.

I was able to integrate the embed lib with Angular, see this codesandbox: 
https://codesandbox.io/s/embed-next-angular-c9n9u

Feel free to use it as a base for your component.

The documentation on CSP headers I linked to explains the console error you shared.

**Comment by AdrienVictor** [comment]
Hello,

Coming back to you with a fix you may not have thought of. 
I checked your example and it is working perfectly. However, when I reproduced it in our production project the styling did not seem to take effect.
Then I noticed that you used basic css in your demo while we are using scss.

I found out that in this case you also need to import the typeform css in the global style.scss file as follow:

@import '@typeform/embed/build/css/widget.css'; //import widget css
@import '@typeform/embed/build/css/popup.css'; // import also popup css

Now it works like a charm :).

Thanks again for the support!
