### ISSUE TITLE
Hidden fields stay empty?

### ISSUE THREAD

**Issue by kwiznix** [Typeform/embed#260]
Hello,

I try to use hidden field but when I look in Postman I see the hidden fields empty?

My code:
`createPopup(formID, {
      size: 90,
      open: "load",
      hidden: {
        customerID: user,
        productArea: RMProductArea,
      },
      onSubmit: (data) => {
        checkResponse(data.responseId);
      },
    });`

both user as RMProductArea are variables with strings as values

if I check in postman for the same responseId in the hidden field part, I see:

`"hidden": {},`

Is this an issue? of am I doing something wrong?

**Comment by mathio** [comment]
Hello @kwiznix 

Since hidden fields can contain sensitive information they are added to the URL hash for security purposes. I think you will not see them in network request (Postman or dev tools) nor will they be logged in any network logs.

If you inspect your page source code you should see an iframe with src - the URL points to your typeform and it should contain `#` sign with hidden fields after it.

Did you set up hidden fields for your typeform in builder?

**Comment by kwiznix** [comment]
Ah right, I see them in that url, for now I dont need them in typeform itself.

What I need to do is get the results of a Typeform with a certain ID, and do some stuff with that data, also I need those 2 values, is there a way to do this with Typeform? but now I think about it, i think I can add that data manually when I am doing that stuff in the code, and dont need typeform to do that for me, thanks for your reply!

**Comment by mathio** [comment]
@kwiznix you should [setup hidden fields in your typeform](https://help.typeform.com/hc/en-us/articles/360052676612-How-to-use-Hidden-Fields) even if you dont need to display the data in the typeform itself. Hidden fields will be included in the results.
