### ISSUE TITLE
`yarn build` fails with error in `inline-style.tsx`

### ISSUE THREAD

**Issue by iampava** [Typeform/embed#295]
Hey! I'm trying to play with this locally to better understand how to use it in our product, but the project fails when trying to build it.

**How to reproduce:**

1. clone project
2. `yarn start` in root
3. `yarn build`

**Error:**
![image](https://user-images.githubusercontent.com/11327761/125820978-7162ae8f-b9ee-4ebe-9fc5-e5a3604448b5.png)

System info:
* Windows 10
* Node v16.1.0

**Comment by mathio** [comment]
Hello @iampava 

I am looking into this and I am unable to replicate the issue. I dont have access to a Windows dev machine at the moment, but it looks like the issue might be with a symlink - the `css` directory is a symlink. Maybe the symlink is not working on Windows? I found [you might need to enable symlinks manually](https://github.community/t/git-bash-symbolic-links-on-windows/522/4)?

**Comment by bhayanishuchi** [comment]
I have similar type of error.
![image](https://user-images.githubusercontent.com/32640339/128610490-c883f8d3-adb0-4e03-aa1d-4a17027cfc22.png)

**Comment by mathio** [comment]
I tried replicating this on Windows 10 in VM and run into the same issue. We should get rid of the symbolic links to make sure this works on all platforms. However this is currently not a priority since in our team everyone is using MacOS or Linux systems.

If you would like to implement new features in embed repo on Windows I'd suggest to look into this issue first. We

**Comment by mathio** [comment]
We do not intend to support Windows machines (without symlink support) for development, at least for now.
