### ISSUE TITLE
BaseOptions `hidden` incompatible with HTMLAttributes

### ISSUE THREAD

**Issue by theycallmeswift** [Typeform/embed#382]
I have a simple button definition that extends the default HTML attributes:

```
export interface ButtonProps extends HTMLAttributes<HTMLElement> {
  // ...
}
```

When I try to use a `PopupButton`, I get the error below because the definition of hidden in `BaseOptions` is incompatible with the standard definition of the hidden attribute.

```
Type error: Type '{ children: ReactNode; defaultChecked?: boolean | undefined; defaultValue?: string | number | readonly string[] | undefined; suppressContentEditableWarning?: boolean | undefined; ... 250 more ...; className: string; }' is not assignable to type 'BaseOptions'.
  Types of property 'hidden' are incompatible.
    Type 'boolean | undefined' is not assignable to type 'Record<string, string> | undefined'.
      Type 'false' is not assignable to type 'Record<string, string> | undefined'.
```

**Comment by mathio** [comment]
Hi @theycallmeswift 

the `hidden` attribute of `PopupButton` component is a `Record`. This record is passed in URL fragment to your form as [hidden fields](https://help.typeform.com/hc/en-us/articles/360052676612-How-to-use-Hidden-Fields).

Right now you can pass only `style`, `className` and `children` to the button component opening the popup embed. 

Would this update help? #383

**Comment by theycallmeswift** [comment]
@mathio not sure if I understand how to use the changes in the update in my code. I'm currently just importing `PopupButton`.  Is the idea here that I should just call the `makeButtonComponent` function directly?

```javascript
import { PopupButton } from "@typeform/embed-react";
// ...
return (
  <PopupButton id={typeformId} autoClose={1} className={classes} {...props}>
    {children}
  </PopupButton>
)
```

My 2¢ here: I'd actually recommend renaming the `hidden` attribute to something else (maybe a data attribute?). In general it feels confusing to create a component that only behaves partially like an HTMLElement.

**Comment by mathio** [comment]
You can pass props for the button like this once the PR is merged:

```
import { PopupButton } from "@typeform/embed-react";
// ...
return (
  <PopupButton id={typeformId} className={classes} buttonProps={{ hidden: true }}>
    {children}
  </PopupButton>
)
```

Changing the name now would mean releasing a backward incompatible version which we dont want to do right now. `PopupButton` does not want to behave partially like an HTMLElement, it just provides a shorthand for `className` and `style` attributes to be passed to the underlying HTML element (eg. `button`). At the time we created it we thought it would be sufficient since you can achieve the same functionality with `style` or `className` as with `hidden` attribute. 

If you need more control (eg use custom element beyond what `@typeform/embed-react` enables) you can use `@typeform/embed` package directly and open the popup manually eg. on click (see ["Advanced Integrations" in this article about the SDK](https://medium.com/typeforms-engineering-blog/building-typeform-react-embed-sdk-e3985efccfc5#b6f2)).
