### ISSUE TITLE
Is Subresource Integrity checking possible with embed.js?

### ISSUE THREAD

**Issue by jasonperrone** [Typeform/embed#388]
I'd like to implement SRI checking for the CDN retrieval of embed.js. Typically that is only possible when the script is static, i.e. a specific version. I am not seeing a way to pull a specific version of embed.js in CDN, so is it even possible to SRI check this library?

**Comment by mathio** [comment]
To pin specific version of this package you can install it locally via `npm` or `yarn`.

If you want to load form CDN and pin specific version you can use https://unpkg.com/

BTW is there a specific reason why you dont want to install it locally?

**Comment by jasonperrone** [comment]
Your last question is the most thought provoking. Since we're doing SRI checking on our scripts necessitating locking to static files, the case for installing it locally becomes pretty compelling. I'll have to talk to the web site managers about that. 

Thanks for pointing me to unpkg as well. That's a great solution if they for some reason don't want to install locally.

**Comment by jasonperrone** [comment]
Well I guess one argument against install locally would be that if I did want to upgrade, I could just bump the version in the that we're including and compute a new sha. I wouldn't have to download the new version. Still though, I would imagine there is a performance improvement hosting it locally.

**Comment by jasonperrone** [comment]
I must be stupid. I cannot figure out the correct unpkg for embed.js. Anyone know it?

**Comment by mathio** [comment]
You can use a URL like this for the JS bundle:
https://unpkg.com/browse/@typeform/embed@1.19.0/build/embed-next.js

You can find other files such as CSS here:
https://unpkg.com/browse/@typeform/embed@1.19.0/build/

> Well I guess one argument against install locally would be that if I did want to upgrade, I could just bump the version in the that we're including and compute a new sha. I wouldn't have to download the new version.

Yes you need to download the new version, however I would not call it an issue since the file size is quite small. If you were to use `yarn` or `npm` it will do everything automatically for you. But I dont know what is your architecture and setup so I can not help more with this.

**Comment by jasonperrone** [comment]
Thank you.

**Comment by DanielGSoftware** [comment]
I also wanted to use SRI and found this thread. It's been a while since this was created, so I'm not sure if it's the right thing to comment here 😅 , but for some reason using unpkg does not work for me. I've tried the url suggested by @mathio, but my typeform does not load: the page remains empty. When using the original url `"https://embed.typeform.com/embed.js"`, it works fine.

**Comment by mathio** [comment]
Hello @DanielGSoftware 

It looks like you need to use URLs like this (for latest version):

```html
<script src="https://unpkg.com/@typeform/embed@5.1.0/build/embed.js"></script>
<link rel="stylesheet" href="https://unpkg.com/@typeform/embed@5.1.0/build/css/widget.css" />
```

I had to remove the `/browse` part of the URL for this to work - you can find this URL via `View Raw` button on _unpkg_. I dont know if this was always the case, or if anything changed with _unpkg_ service recently.

**Comment by DanielGSoftware** [comment]
@mathio worked like a charm, thank you!
