### ISSUE TITLE
How can I add multiple popup form in a single html page?

### ISSUE THREAD

**Issue by compiled-krishan** [Typeform/embed#509]
I tried making two buttons with different ids and my javascript looked like- 
const { open, close, toggle, refresh } = window.tf.createPopup('myformid');
document.querySelector('#quote-btn').onclick = toggle;
const { open, close, toggle, refresh } = window.tf.createPopup('myformid');
document.querySelector('#contact-btn').onclick = toggle;

But it didn't work out. Please help me with this

**Comment by mathio** [comment]
Hello @compiled-krishan 

since you didn't provide any additional information I am going to assume the simplest use case - that you are using the lib from our CDN.

You need:
* the buttons
* include embed lib - JS and related CSS
* the code to trigger the popup (you need each popup in a separate variable, if you spread both the names `open, close, toggle, refresh`  will clash since they are defined as constants)

```
<button id="quote-btn">quote</button>
<button id="contact-btn">contact</button>

<script src="//embed.typeform.com/next/embed.js"></script>
<link rel="stylesheet" href="//embed.typeform.com/next/css/popup.css" />

<script>
  const quoteForm = window.tf.createPopup('my-quote-form-id');
  document.querySelector('#quote-btn').onclick = quoteForm.toggle

  const contactForm = window.tf.createPopup('my-contact-form-id');
  document.querySelector('#contact-btn').onclick = contactForm.toggle;
</script>
```

If you want to display the same typeform for each button you can create the popup just once:
```
  const {toggle} = window.tf.createPopup('my-quote-and-contact-form-id');
  document.querySelector('#quote-btn').onclick = toggle
  document.querySelector('#contact-btn').onclick = toggle;
```

If you were to **embed via HTML-only** you can do it in 3 lines like this:
```
<button data-tf-popup="my-quote-form-id">quote</button>
<button data-tf-popup="my-contact-form-id">contact</button>
<script src="//embed.typeform.com/next/embed.js"></script>
```

**Comment by compiled-krishan** [comment]
Both the ways worked out. Thank You!
