### ISSUE TITLE
Incorrect Typeform types for onSubmit

### ISSUE THREAD

**Issue by AaronLayton** [Typeform/embed#577]
Are the the typescript types wrong here?

https://github.com/Typeform/embed/blob/e58cd98e0086bd8c2fd6c602875472b8d52fbe94/packages/embed/src/base/actionable-options.ts#L6-L12

The JSDoc states a payload with only a `responseId` but on the documentation site it states you will get `responseId` and `formId` - see https://www.typeform.com/developers/embed/callbacks/#on-submit

```typescript
createPopup('<form-id>', {
  onSubmit: ({ formId, responseId }) => {
    console.log(`Form ${formId} submitted, response id: ${responseId}`)
  },
})
```

In VSCode the TypeScript intellisense overlay also suggests you will only get the `responseId`

![image](https://user-images.githubusercontent.com/694964/233163072-bf494e87-f8cf-4b32-82ae-e3d4242712b3.png)

Upon my testing, this is clearly not the case as I get the below from the props when the `onSubmit` is called

```javascript
{
  response_id: 'gzpqhq1so2obvheegzpqhieczjbh82qm', 
  responseId: 'gzpqhq1so2obvheegzpqhieczjbh82qm', 
  formId: 'MmvHZJQV'
}
```

**Comment by AaronLayton** [comment]
Just to note, it would be really useful to get a copy of the questions and answers that have been submitted here along with the `reponseId` - not only will this save me having to call off to the **Response API** it will allow me to take actions for the user straight away - Another issue I am sure

**Comment by mathio** [comment]
Hello @AaronLayton 

You are right, the types are incorrect. Correct type should be:

```
interface Payload {
  responseId: string
  formId: string
}
```

The `response_id` is present for backward compatibility, has the same value as `responseId`. I am not sure if we can break the backward compatibility but I will look into it, I agree it is a bit confusing.


Unfortunately we are unable to pass the response to `onSubmit` callback because submissions are processed asynchronously and might not be saved at the time the form is submitted.
