### ISSUE TITLE
Get answers for an embedded form without server side APIs / access tokens

### ISSUE THREAD

**Issue by binarymonkey84** [Typeform/embed#637]
We're personalising post-Typeform redirect pages to include "First name" data that was submitted in the form.

To do that, we added a variable in the redirect URL ([like the help article suggests](https://www.typeform.com/help/a/use-variables-in-redirect-links-4414707303700/)).

Unfortunately this creates data privacy problems, since URLs containing personal data are then sent to various tracking providers like Meta and Google. We have had warnings from these vendors about it.

One solution would be to retrieve answer data via the Embed SDK so we can store it in local storage instead, but the the Embed SDK doesn't appear to support this. The alternative, the Responses API, necessitates setting up a complex server-side application.

Will Typeform bring this capability to the Embed SDK, or is it not something that will be considered?

I notice a few similar services do appear to offer this functionality, FYI.

**Comment by mathio** [comment]
Hello @binarymonkey84 

we do not plan to support a feature like this for the embed SDK at the moment. Since responses are processed asynchronously, the only way to retrieve data is via [Responses API](https://www.typeform.com/developers/responses/) (as you mentioned).

Out of curiosity, could you please link to some docs of the similar services you mentioned? Thanks.

**Comment by binarymonkey84** [comment]
@mathio Sure, here's an example from Paperform:

https://paperform.co/help/articles/embedded-form-submissions/

Typeform does have a similar [onSubmit callback](https://www.typeform.com/developers/embed/callbacks/#on-submit), but stops short of providing the data that was in the form. Why don't you you just provide the answer data in this callback?

> Since responses are processed asynchronously, the only way to retrieve data is via [Responses API](https://www.typeform.com/developers/responses/) (as you mentioned).

I'm not sure what influence server side processing has on this use case, since we're just talking about extracting the data that's already local on the client side.

**Comment by mathio** [comment]
Let me discuss this with the team. I will get back to you soon  🤞

**Comment by mathio** [comment]
Hello @binarymonkey84 

I am sorry, but we have decided we will not be providing this feature at the moment.

There is some security risk tied to this. If we pass this payload in `onSubmit` callback, any website that embeds a typeform would be able to read responses. At the moment host website does not have access to embedded typeform or any responses since it is inside an iframe. Malicious websites might display fake forms even right now and collect data, however by building this feature we would make it easier for potential attackers and allow them to use actual typeforms to execute the attack.

**Comment by binarymonkey84** [comment]
Sounds like that concern could be pretty easily addressed by having an authorised hosts / domains list in the Typeform account?

In your iframe, you can just query what host is embedding the frame (via [window.parent](https://developer.mozilla.org/en-US/docs/Web/API/Window/parent).location) and if it's on the authorised list, you can be safe in passing back responses. 

Maybe that would work well?

**Comment by mathio** [comment]
We considered a whitelisting feature, but decided not to go forward with the idea. Other than that, there are also some challenges in reliably determining host page URL.

----

A script from the iframe does have access to `window.parent.location`, but it can not read any of its values: 
```
Uncaught DOMException: Failed to read a named property 'href' from 'Location': Blocked a frame with origin "https://***" from accessing a cross-origin frame.
```

We can not reliably use [document.referrer](https://developer.mozilla.org/en-US/docs/Web/API/Document/referrer) either, as it depends on the browser and might not be present. 

In some browsers we might be able to use [ancestorOrigins](https://developer.mozilla.org/en-US/docs/Web/API/Location/ancestorOrigins), however it is not supported by all browsers.

**Comment by binarymonkey84** [comment]
Perhaps [`event.origin`](https://developer.mozilla.org/en-US/docs/Web/API/MessageEvent/origin) on a cross-origin window message could be used to verify the host instead? MDN even [suggests this here](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage#security_concerns), and [browser support looks good](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage#browser_compatibility).

The Embed SDK code could call [`postMessage`](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage) to send a message to the Typeform iframe, like "verifyhost" or something. If you're already using `postMessage` to set up callbacks with the Embed SDK, just use the existing calls.

Then on the Typeform side, [listen for the message](https://developer.mozilla.org/en-US/docs/Web/API/Window/message_event) and if `event.origin` matches a domain that's been whitelisted on the Typeform account, then include the response data in the `onSubmit` callback.

Surely that's a winner? 🤞

**Comment by mathio** [comment]
Yes that solution sounds solid.

However, as I mentioned in my previous comment, we decided not to implement this feature at the moment.

**Comment by binarymonkey84** [comment]
Oh, I thought that decision was only based on the fact Typeform didn't want response data available to non whitelisted hosts. If my suggested approach solves that, why not reconsider?

I have noticed quite a few developers struggle with the same problem when I was researching how to do this on Stack Overflow, etc.

Typeform is difficult to recommend to our agency clients who want embedded forms on their sites which can then redirect to a personalised landing page, so this relatively simple improvement would make a world of difference.

**Comment by mathio** [comment]
Thank you for the comment. Although we are not working on this feature, we might plan it in the future.

**Comment by jybleau** [comment]
This is the reason we could not actively use Typeform anymore, sadly.
We have asked for this feature a few times via support request years ago.

@binarymonkey84 propositions seems sound.

FYI, Vimeo is doing something similar with their embedded player to only allow embedding on domains on a whitelist, very useful.

It seems they use the referrer header because if the client has something like a "tracker blocker" that modify this header (or has enable "extreme" privacy setting in a browser like Brave), then the embedding validation fails and cannot load the video.

Having a plugin or an application modifying this kind of headers is never recommended anyway (these apps show disclaimers about that).
In our use case, when it very rarely occurs, we simply ask our clients to change their settings.

Thanks
